import warnings
import torch
import cv2
import random
import os
from torchvision import transforms
from YOLO_with_ResNet50 import YOLOv3
from pycocotools.coco import COCO

# Since YOLOv3 uses logger.py, each detection run will create a new log file in "logs" folder

# Warning imports are to avoid the expandable_segments warnings on Windows
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", message="expandable_segments not supported")

# COCO label mapping (model index -> name)
coco_annotation_file = r"C:\Users\viktor.acs\Downloads\coco_dataset\annotations\instances_val2017.json"
coco = COCO(coco_annotation_file)

# Get sorted COCO category IDs (non-contiguous -> remap to contiguous 0–79)
coco_category_ids = sorted(coco.getCatIds())
coco_id_to_model_index = {coco_id: idx for idx, coco_id in enumerate(coco_category_ids)}

# Build model_index -> class_name mapping
coco_classes = {
    coco_id_to_model_index[cat["id"]]: cat["name"]
    for cat in coco.loadCats(coco_category_ids)
}

# Paths
checkpoint_path = "yolov3_checkpoint_last_epoch.pth"

# For COCO val images
# image_dir = r"C:\Users\viktor.acs\Downloads\coco_dataset\val2017"

# For custom images
image_dir = r"C:\Users\viktor.acs\Downloads\coco_dataset\test_images"

# Load checkpoint
checkpoint = torch.load(checkpoint_path, map_location="cuda", weights_only=False)
num_classes = 80
"""
# Default anchors
anchors = [
    [10, 13], [16, 30], [33, 23],
    [30, 61], [62, 45], [59, 119],
    [116, 90], [156, 198], [373, 326]
]

"""
# K-means generated by k_means_anchor_calculator.py on the resized COCO dataset (416x416):
anchors = [
    [19.39769772, 24.12491592], [40.91803117, 76.44313414], [113.50188071, 69.27488936],
    [71.71268453, 161.95265297], [105.08463053, 285.58598963], [191.49338089, 161.76429439],
    [351.54059713, 159.67305114], [224.41982096, 331.08204223], [381.16142647, 359.7244103]
]

# Small (52x52) -> Stride 8, Medium (26x26) -> Stride 16, Large (13x13) -> Stride 32
strides = [8, 16, 32]  


# scaled_anchors are provided in grid units
scaled_anchors = [
    (w / strides[0], h / strides[0]) for w, h in anchors[:3]   # Small scale (52x52)
    ] + [
        (w / strides[1], h / strides[1]) for w, h in anchors[3:6]  # Medium scale (26x26)
    ] + [
        (w / strides[2], h / strides[2]) for w, h in anchors[6:]   # Large scale (13x13)
    ]

# Build model
model = YOLOv3(num_classes=num_classes, anchors=anchors)
model.load_state_dict(checkpoint["model_state_dict"])
model.to("cuda").eval()

# Only look for image files 
valid_exts = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

image_files = [
    f for f in os.listdir(image_dir)
    if os.path.isfile(os.path.join(image_dir, f))
    and os.path.splitext(f.lower())[1] in valid_exts
]

if not image_files:
    raise RuntimeError(f"No valid image files found in {image_dir}")

# Pick a random image
random_file = random.choice(image_files)
image_path = os.path.join(image_dir, random_file)
print(f"[I] Running inference on {image_path}")

# Load and preprocess image (keep original size for drawing later)
orig_img = cv2.imread(image_path)
if orig_img is None:
    raise RuntimeError(f"OpenCV could not read image: {image_path}")

orig_h, orig_w = orig_img.shape[:2]

# Preprocess for YOLO 416x416
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Resize((416, 416)), 
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])
img_rgb = cv2.cvtColor(orig_img, cv2.COLOR_BGR2RGB)
input_tensor = transform(img_rgb).unsqueeze(0).to("cuda")

# Forward pass
with torch.no_grad():
    outputs = model(input_tensor)

# Decode predictions
preds = model.decode_predictions(
    outputs,
    anchors=scaled_anchors,
    num_classes=num_classes,
    # image_w=orig_w,
    # image_h=orig_h,
    image_w = 416,
    image_h = 416,
    conf_threshold=0.95,
    nms_threshold=0.1,
    debug_force_class=None
)

# preds is a list of dictionaries -> take the first one (batch size = 1)
pred = preds[0]
boxes = pred["boxes"].cpu().numpy()
scores = pred["scores"].cpu().numpy()
labels = pred["labels"].cpu().numpy()

# Rescale boxes from 416 to original image size
sx = orig_w / 416.0
sy = orig_h / 416.0
boxes[:, [0, 2]] *= sx
boxes[:, [1, 3]] *= sy

# Draw predictions with class names and scores with filled background (YOLO style), inside the bbox (bottom-left corner) if it fits, otherwise above the box 
for (x1, y1, x2, y2), conf, cls in zip(boxes, scores, labels):
    class_name = coco_classes.get(int(cls), f"id_{int(cls)}")
    label_text = f"{class_name}: {conf:.2f}"

    # Bbox and box color (green)
    color = (0, 255, 0)

    # Sanity (cip coordinates to image boundaries)
    # H, W = orig_img.shape[:2]
    H, W = orig_h, orig_w
    x1 = max(0, min(int(x1), W - 1))
    y1 = max(0, min(int(y1), H - 1))
    x2 = max(0, min(int(x2), W - 1))
    y2 = max(0, min(int(y2), H - 1))

    box_w, box_h = int(x2 - x1), int(y2 - y1)

    # Adaptive font scale based on box height
    font_scale = max(0.2, min(0.4, box_h / 120))
    thickness = 1

    # Compute text size
    (text_w, text_h), _ = cv2.getTextSize(label_text, cv2.FONT_HERSHEY_SIMPLEX, font_scale, thickness)

    # Choose position: inside the bbox (bottom-left corner) or above bbox
    if text_h + 4 < box_h and text_w + 4 < box_w:
        text_x = int(x1)
        text_y = int(y2)
    else:
        text_x = int(x1)
        text_y = max(0, int(y1) - 5)

    # Draw bounding box
    cv2.rectangle(orig_img, (int(x1), int(y1)), (int(x2), int(y2)), color, 1)

    # Draw filled rectangle for text background
    cv2.rectangle(
        orig_img,
        (text_x, text_y - text_h - 4),
        (text_x + text_w + 2, text_y),
        color,
        -1,
    )

    # Transparent background for text
    overlay = orig_img.copy()
    cv2.rectangle(
        overlay,
        (text_x, text_y - text_h - 4),
        (min(text_x + text_w + 2, W - 1), text_y),
        color,
        -1,
    )
    alpha = 0.0  # transparency factor (0: 100% transparent, 1: 100% opaque)
    orig_img = cv2.addWeighted(overlay, alpha, orig_img, 1 - alpha, 0)

    # Put black text on the green background
    cv2.putText(
        orig_img,
        label_text,
        (text_x + 1, text_y - 3),
        cv2.FONT_HERSHEY_SIMPLEX,
        font_scale,
        (0, 0, 0),
        thickness,
        cv2.LINE_AA,
    )

# Save and show
out_path = "prediction_result.jpg"
cv2.imwrite(out_path, orig_img)
print(f"[I] Saved visualization to {out_path}")
